pipeline {
    agent any
    stages {
        stage('Build Docker Image') {  
            steps{                     
                echo 'Building Docker Image....'
                sh 'docker-compose build'               
            }           
        }
        stage('Run image') {
            steps {
                echo 'Running image....'
                sh 'docker-compose up -d'
            }
        }
    }
}